### PR TITLE
ACNA-348 - Shared actions in a sequence

### LINKED ISSUE #27: ACNA-348 - Cannot create a sequence out of actions from shared packages
**Describe the bug**
I have a shared package in 'sharednamespace' and i am trying to create a sequence in 'mynamespace' namespace under 'mypackage' package using actions from the shared package.
The above results in error because deploy command prepends '/mynamespace' to the actions in the sequence. This works fine with the openwhisk rest api.

**To Reproduce**
Put the following in manifest.yml and run 'aio runtime deploy'
packages:
  mypackage:
    sequences:
      authenticate:
        actions: '/sharednamespace/sharedpackage/login'
        web: 'yes'

**Expected behavior**
Sequence should be created.

**Screenshots**
NA

### PR DESCRIPTION
**Pull request by Himavanth**
Support for shared actions in a sequence.
The following in a manifest was not working earlier but will work now with deploy command.
packages:
mypackage:
sequences:
authenticate:
actions: '/sharednamespace/sharedpackage/login'
web: 'yes'

Closes #27 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/runtime-helpers.js [hunk 1]
```diff
@@ -502,16 +533,18 @@ async function deployPackage (entities, ow, logger) {
...
+    await ow.packages.update(pkg)
     logger(`Info: package [${pkg.name}] has been successfully deployed.\n`)
   }
   for (let action of entities.actions) {
     if (action['exec'] && action['exec']['kind']) {
       action['exec']['components'] = action['exec']['components'].map(sequence => {
-        return `/${ns}/${sequence}`
+        let actionItemCount = sequence.split('/').length
+        let startsWithSlash = sequence.startsWith('/')
+        return (startsWithSlash && actionItemCount > 3) || (!startsWithSlash && actionItemCount > 2)
```
Comment (shazron) [inline src/runtime-helpers.js]: This part of the code is very unclear. perhaps I'm misunderstanding the test inputs, let me know.

If ns = 'mynamespace'

Test sequences:
1. `/one/two/three/four` (true case)
2. `one/two/three` (true case)
3. `one/two` (false case)
4. `/one/two/three` (false case)

Will return:
1. `//one/two/three/four`
2. `/one/two/three`
3. `/mynamespace/one/two`
4. `/mynamespace//one/two/three`

Are these the intended results? Perhaps this should be broken out in its own function and unit-tested just in case.

Comment (Himavanth) [reply src/runtime-helpers.js]: Thx @shazron for the review. You are right about the cases except the fourth which is actually a 'true case'. Here is a simple explanation. If there are three parts in the "action path", the first part is the namespace and we don't have to append namespace to it. I will add some comments in the code and also change the test a little so it's more clear.

Comment (shazron) [reply src/runtime-helpers.js]: Ah ok, now I get what was intended. 

Actually I was demonstrating what your code will output, if you input my test sequences. If you look at your `if` statement, the fourth item is false case: startsWithSlash is `true` and actionItemCount is `3`, which will not satisfy any of the clauses.

Comment (Himavanth) [reply src/runtime-helpers.js]: Actually the actionItemCount is 4 in this case. Nevertheless, i have simplified that part of code. Please take a look. 🙂

Comment (shazron) [reply src/runtime-helpers.js]: Oops. Ah yes, there is an empty string. My bad :)
```
$ "/one/two/three".split('/')
["", "one", "two", "three"] 
```
